CREATE TABLE IF NOT EXISTS project (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title TEXT,
	category TEXT,
	funding_goal INTEGER,
	start_date DATE,
	end_date DATE
);

CREATE TABLE IF NOT EXISTS user (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name TEXT,
	age INTEGER
);

CREATE TABLE IF NOT EXISTS pledge (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	amount INTEGER,
	user_id INTEGER REFERENCES user,
	project_id INTEGER REFERENCES project
)